### ISSUE TITLE
Fails to load, import error

### ISSUE THREAD

**Issue by aurel-g** [bombax-xiaoice/ComfyUI-MagicDance#3]
```
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-MagicDance/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-MagicDance/nodes.py", line 20, in <module>
    from model_lib.ControlNet.cldm.model import create_model
ModuleNotFoundError: No module named 'model_lib.ControlNet'
```

**Comment by aurel-g** [comment]
Thanks for merging
